sudo: required
dist: trusty
notifications:
  email: false
language: ruby
cache:
  bundler: true
rvm:
  - 2.4.1
addons:
  apt:
    packages:
    - xvfb
  chrome: stable
  code_climate:
    repo_token: 431e13a58615c311ea53fd104db553d633d96018687949d0b3423ace9b4ccf47
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost &
  - gem install images_by_url
script:
  - BROWSER_MIN=on ENV=test bundle exec rspec
  - bundle exec codeclimate-test-reporter
